#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"

"$HOME"/.config/yabai/create_spaces.sh

# Move space 7 to the second display when it's connected
# yabai -m space 7 --display 2
# Assign space 7 to the second display
# yabai -m display --add 2 --space 7

yabai -m config external_bar all:40:0 \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_zoom_persist off \
  window_placement second_child \
  window_shadow float \
  window_opacity off \
  window_opacity_duration 0.2 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.8 \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_quint \
  insert_feedback_color 0xff9dd274 \
  split_ratio 0.50 \
  auto_balance off \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  \
  top_padding 8 \
  bottom_padding 8 \
  left_padding 8 \
  right_padding 8 \
  window_gap 10

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autoraise

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config layout bsp

# move some apps automatically to specific spaces
yabai -m rule --add app="Google Chrome" space=^1
yabai -m rule --add app="Ghostty" space=2
yabai -m rule --add app="Telegram" space=3
yabai -m rule --add app="StrelkaChat" space=3
yabai -m rule --add app="Notes" space=4
yabai -m rule --add app="Reminders" space=4
yabai -m rule --add app="Mail" space=^5
yabai -m rule --add app="Calendar" space=^5

echo "yabai configuration loaded.."
